### PR TITLE
added socal434.md to contributors 

### PR DESCRIPTION
**Pull request by socal434**

### CODE REVIEW

**Comment by kerolloz** [comment]
@socal434 
please delete `.DS_Store` files!
I don't get why did you edit ` contributors/nikznk/nikznk.md ` this is not your file! please undo the changes

**Comment by socal434** [comment]
I copied the format from that file and accidentally erased some of it. It is fixed now. I don't know how to delete the .DS_Store files

**Review by kerolloz — CHANGES_REQUESTED** [review]
also delete `contributors/.DS_Store`

**Comment by socal434** [comment]
I think that the file is gone now. I don't see it in the Files Changed tab. I hope that it is good.

**Comment by kerolloz** [comment]
@socal434 
Thank you for contributing and your patience :smile:

**Review by kerolloz — APPROVED** [review]

**Pull request merged**
